name: ds2500
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - seaborn
  - scikit-learn
  - xgboost=3.0.2
  - matplotlib
  - shap
  - rdkit
  - jupyterlab
  - pip
  - pip:
      - slicer