name: ds2500
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.1
  - numpy=1.26.0
  - numpydoc=1.5.0
  - scikit-learn=1.3.2
  - scipy=1.11.2
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - ipykernel=6.25.2
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-lsp-black=1.3.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.7.2
  - python-slugify=8.0.1
  - python-tzdata=2023.3
  - python.app=1.4
  - python_abi=3.10
  - pip:
    - contourpy==1.2.0
    - gradescope-utils==0.5.0
    - llvmlite==0.44.0
    - matplotlib==3.8.2
    - numba==0.61.2
    - pyqt5-sip==12.11.0
    - rdkit==2025.3.2
    - shap==0.47.2
    - slicer==0.0.8
    - xgboost==3.0.2
